[package]
name = "bevy_spatial_boids"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.0"
halton = "0.2.1"
kiddo = { version = "4.2.0" }
rand = "0.9.0-alpha.1"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
